/*
    Generated by Atomist on 05 07 2016 
*/
package vehicleData.retriever;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class VehicleDataRetrieverApplication {

    public static void main(String[] args) {
        SpringApplication.run(VehicleDataRetrieverApplication.class, args);
    }
}
